name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  switch-build:
    name: Switch build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build commands inside Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace devkitpro/devkita64:latest bash -c "
            cd /workspace &&
            export DEVKITPRO=/opt/devkitpro &&
            export DEVKITA64=/opt/devkitpro/devkitA64 &&
            export PATH=\$DEVKITA64/bin:\$DEVKITPRO/tools/bin:\$PATH &&
            mkdir -p build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain/switch.cmake -DNX=ON &&
            make -j\$(nproc)
          "

      - name: Create zip with binaries
        run: |
          DATE_TIME=$(date +'%Y-%m-%d_%H-%M-%S')
          zip -j "fallout-ce_${DATE_TIME}.zip" build/fallout-ce.nro build/fallout-ce.nso

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fallout-ce
          path: |
            fallout-ce_*.zip